// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8wuAgA6WtHq069RjcUpGLigOROItJIs',
    appId: '1:996182230556:web:606ca645887a82ce8fc1d9',
    messagingSenderId: '996182230556',
    projectId: 'connect-ngo-82057',
    authDomain: 'connect-ngo-82057.firebaseapp.com',
    storageBucket: 'connect-ngo-82057.firebasestorage.app',
    measurementId: 'G-8301BMWM9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1aYGsSiFBVEeJFzIvtJa6ySYGDm7_Z8',
    appId: '1:996182230556:android:4b11e2f32447fc998fc1d9',
    messagingSenderId: '996182230556',
    projectId: 'connect-ngo-82057',
    storageBucket: 'connect-ngo-82057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15240GbMinUQKT85TgbZ2cJB4gYBmweU',
    appId: '1:996182230556:ios:d6450cf4d962f1508fc1d9',
    messagingSenderId: '996182230556',
    projectId: 'connect-ngo-82057',
    storageBucket: 'connect-ngo-82057.firebasestorage.app',
    iosBundleId: 'com.example.ngoApp',
  );

}